config_cropping_model:
  name: cropping_model
  size: 128
  batch_size: 8
  lr: 0.0043
  base_dim: 16
  depth: 6
  loss_type: dice
  importance: 1.666
  normalize_images: True
  training_dataset_size: 500
  growth_factor: 1.6
  ratio: 1


config_segmentation_model:
  name: segmentation_model
  size: 128
  batch_size: 8
  lr: 0.0008
  base_dim: 40
  depth: 5
  loss_type: dice
  importance: 1.5
  normalize_images: True
  training_dataset_size: 1000
  growth_factor: 1.8
  ratio: 0

wandb_sweep:
  name: "Segmentation Sweep"
  method: random
  metric:
    name: val_loss
    goal: minimize
  parameters:
    name:
      value: sweep
    size:
      value: 128
    normalize_images:
      value: true
    batch_size:
      distribution: q_uniform
      min: 2
      max: 12
      q: 1
    importance:
      value: 1.5
    lr:
      distribution: uniform
      min: 0.0001
      max: 0.01
    loss_type:
      values: [ CCE, dice, focal ]
    training_dataset_size:
      value: 400
    growth_factor:
      distribution: uniform
      min: 1.5
      max: 2.2
    depth:
      values: [ 3, 4, 5, 6 ]
    base_dim:
      distribution: q_uniform
      min: 10
      max: 100
      q: 1
    ratio:
      value: 0
  run_cap: 100
#  early_terminate:
#    type: hyperband
#    s: 3          # Number of brackets
#    eta: 3        # Bracket multiplier
#    min_iter: 6   # Minimum iterations for the first bracket
#    max_iter: 30

best_model_cropping:
  in_channels: 3
  base_dim: 64
  dropout: 0.3
  batch_norm: true
  state_dict_path: models\\best_model_3.pt

paths:
  data_path: 'C:\\my files\\REFUGE'
  train_images_path: 'Training400'
  train_masks_path: 'Annotation-Training400/Disc_Cup_Masks'
  val_images_path: 'REFUGE-Validation400'
  val_masks_path: 'REFUGE-Validation400-GT'
  test_images_path: 'REFUGE-Test400'
  test_masks_path: 'REFUGE-Test-GT'
